### ISSUE TITLE
Transfer repo to cldf org

### ISSUE THREAD

**Issue by xrotwang** [SimonGreenhill/lexibuildbot#3]
I'd say we call this `cldf-buildbot` right away. Should work for all `cldfbench` curated datasets.

**Comment by xrotwang** [comment]
Or maybe we start over with a fresh repos: https://github.com/cldf/cldf-buildbot ?

**Comment by SimonGreenhill** [comment]
Whatever works.  I think the only thing in here is master.cfg and the README.md.

**Comment by SimonGreenhill** [comment]
(i.e. probably easier to start over, unless you want those issues migrated too)

**Comment by xrotwang** [comment]
agree: https://github.com/cldf/cldf-buildbot
