### ISSUE TITLE
Accessing catalogs from the workers

### ISSUE THREAD

**Issue by xrotwang** [SimonGreenhill/lexibuildbot#4]
It seems that the simplest way to access catalogs (like Glottolog) from shell commands run on the workers would be as follows:
- run all workers on the same machine
- have clones of the catalogs on this machine
- pass the location of the clones to the workers via `env` variables.

Note: This would require `cldfbench` to read these `env` variables.

There could be an `appconfig` fab task to update the catalogs.

**Comment by SimonGreenhill** [comment]
copied to https://github.com/cldf/cldf-buildbot/issues/3
